return {
  {
    "rose-pine/neovim",
    name = "rose-pine",
    lazy = false,
    priority = 1000,
    opts = {
      variant = "auto",
      dark_variant = "main",
      dim_inactive_windows = false,
      extend_background_behind_borders = true,
      styles = {
        bold = true,
        italic = false,
        transparency = true,
      },
      palette = {
        main = {
          _nc = "#282e38",
          base = "#2e3440",
          surface = "#3b4252",
          overlay = "#434c5e",
          muted = "#4c566a",
          subtle = "#616e88",
          text = "#d8dee9",
          love = "#bf616a",
          gold = "#ebcb8b",
          rose = "#88c0d0",
          pine = "#81a1c1",
          foam = "#8fbcbb",
          iris = "#b48ead",
          leaf = "#a3be8c",
          highlight_low = "#3b4252",
          highlight_med = "#434c5e",
          highlight_high = "#4c566a",
        },
        dawn = {
          _nc = "#e5e9f0",
          base = "#eceff4",
          surface = "#e5e9f0",
          overlay = "#d8dee9",
          muted = "#848c9d",
          subtle = "#4c566a",
          text = "#2e3440",
          love = "#bf616a",
          gold = "#ebcb8b",
          rose = "#88c0d0",
          pine = "#81a1c1",
          foam = "#8fbcbb",
          iris = "#b48ead",
          leaf = "#a3be8c",
          highlight_low = "#e5e9f0",
          highlight_med = "#d8dee9",
          highlight_high = "#aeb5c3",
        },
      },
      groups = {
        git_add = "leaf",
        git_change = "gold",
        git_dirty = "gold",
      },
      highlight_groups = {
        Boolean = { fg = "pine" },
        Character = { fg = "leaf" },
        Float = { fg = "iris" },
        Number = { fg = "iris" },
        String = { fg = "leaf" },
      },
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "rose-pine",
    },
  },
}
