#!/bin/sh
# Agent state hooks are generated by herdr itself, never vendored here, so they
# always match the installed herdr version. Re-run after a herdr upgrade with:
#   herdr integration install omp
set -eu

command -v herdr >/dev/null || exit 0

herdr integration install omp || echo "herdr integration install omp failed" >&2

herdr integration status
