#!/bin/sh
# Agent state hooks are generated by herdr itself, never vendored here, so they
# always match the installed herdr version. Re-run after a herdr upgrade with:
#   herdr integration install <omp|claude|codex>
set -eu

command -v herdr >/dev/null || exit 0

for target in omp claude codex; do
	herdr integration install "$target" || echo "herdr integration install $target failed" >&2
done

herdr integration status
