return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    lazy = false,
    priority = 1000,
    config = function()
      require("catppuccin").setup({
        background = {
          light = "latte",
          dark = "mocha",
        },
        color_overrides = {
          latte = {
            rosewater = "#2e3440",
            flamingo = "#2e3440",
            red = "#bf616a",
            maroon = "#bf616a",
            pink = "#b48ead",
            mauve = "#b48ead",
            peach = "#d08770",
            yellow = "#ebcb8b",
            green = "#a3be8c",
            teal = "#8fbcbb",
            sky = "#88c0d0",
            sapphire = "#88c0d0",
            blue = "#81a1c1",
            lavender = "#5e81ac",
            text = "#2e3440",
            subtext1 = "#3b4252",
            subtext0 = "#434c5e",
            overlay2 = "#4c566a",
            overlay1 = "#687183",
            overlay0 = "#848c9d",
            surface2 = "#99a1b0",
            surface1 = "#aeb5c3",
            surface0 = "#c3cad6",
            base = "#eceff4",
            mantle = "#e5e9f0",
            crust = "#d8dee9",
          },
          mocha = {
            rosewater = "#d8dee9",
            flamingo = "#d8dee9",
            red = "#bf616a",
            maroon = "#bf616a",
            pink = "#b48ead",
            mauve = "#b48ead",
            peach = "#d08770",
            yellow = "#ebcb8b",
            green = "#a3be8c",
            teal = "#8fbcbb",
            sky = "#88c0d0",
            sapphire = "#88c0d0",
            blue = "#81a1c1",
            lavender = "#5e81ac",
            text = "#d8dee9",
            subtext1 = "#bac2d1",
            subtext0 = "#9ca6b8",
            overlay2 = "#616e88",
            overlay1 = "#566279",
            overlay0 = "#4c566a",
            surface2 = "#485164",
            surface1 = "#434c5e",
            surface0 = "#3b4252",
            base = "#2e3440",
            mantle = "#282e38",
            crust = "#232831",
          },
        },
        transparent_background = true,
        show_end_of_buffer = false,
        integration_default = false,
        integrations = {
          barbecue = { dim_dirname = true, bold_basename = true, dim_context = false, alt_background = false },
          cmp = true,
          gitsigns = true,
          hop = true,
          illuminate = { enabled = true },
          native_lsp = { enabled = true, inlay_hints = { background = true } },
          neogit = true,
          neotree = true,
          semantic_tokens = true,
          treesitter = true,
          treesitter_context = true,
          vimwiki = true,
          which_key = true,
        },
        highlight_overrides = {
          all = function(colors)
            return {
              CmpItemMenu = { fg = colors.surface2 },
              CursorLine = { bg = colors.surface0 },
              CursorLineNr = { fg = colors.text },
              FloatBorder = { bg = "NONE", fg = colors.base },
              GitSignsChange = { fg = colors.yellow },
              Island = { bg = colors.base },
              IslandNC = { bg = colors.mantle },
              LineNr = { fg = colors.overlay0 },
              LspInfoBorder = { link = "FloatBorder" },
              MsgArea = { bg = "NONE" },
              NeoTreeDirectoryIcon = { fg = colors.subtext1 },
              NeoTreeDirectoryName = { fg = colors.subtext1 },
              NeoTreeFloatBorder = { link = "TelescopeResultsBorder" },
              NeoTreeGitConflict = { fg = colors.red },
              NeoTreeGitDeleted = { fg = colors.red },
              NeoTreeGitIgnored = { fg = colors.overlay0 },
              NeoTreeGitModified = { fg = colors.yellow },
              NeoTreeGitStaged = { fg = colors.green },
              NeoTreeGitUnstaged = { fg = colors.red },
              NeoTreeGitUntracked = { fg = colors.green },
              NeoTreeIndent = { fg = colors.surface1 },
              NeoTreeNormal = { link = "Island" },
              NeoTreeNormalNC = { link = "IslandNC" },
              NeoTreeRootName = { fg = colors.subtext1, style = { "bold" } },
              NeoTreeTabActive = { fg = colors.text, bg = colors.base },
              NeoTreeTabInactive = { fg = colors.surface2, bg = colors.mantle },
              NeoTreeTabSeparatorActive = { fg = colors.base, bg = colors.base },
              NeoTreeTabSeparatorInactive = { fg = colors.mantle, bg = colors.mantle },
              NeoTreeWinSeparator = { link = "WinSeparator" },
              NormalFloat = { bg = colors.base },
              Pmenu = { bg = colors.mantle, fg = "" },
              PmenuSel = { bg = colors.surface0, fg = "" },
              StatusLine = { bg = "NONE", fg = colors.overlay1 },
              StatusLineNC = { bg = "NONE", fg = colors.surface2 },
              TabLineFill = { bg = "NONE" },
              TelescopePreviewBorder = { bg = colors.crust, fg = colors.crust },
              TelescopePreviewNormal = { bg = colors.crust },
              TelescopePreviewTitle = { fg = colors.crust, bg = colors.crust },
              TelescopePromptBorder = { bg = colors.surface0, fg = colors.surface0 },
              TelescopePromptCounter = { fg = colors.mauve, style = { "bold" } },
              TelescopePromptNormal = { bg = colors.surface0 },
              TelescopePromptPrefix = { bg = colors.surface0 },
              TelescopePromptTitle = { fg = colors.surface0, bg = colors.surface0 },
              TelescopeResultsBorder = { bg = colors.mantle, fg = colors.mantle },
              TelescopeResultsNormal = { bg = colors.mantle },
              TelescopeResultsTitle = { fg = colors.mantle, bg = colors.mantle },
              TelescopeSelection = { bg = colors.surface0 },
              WhichKeyFloat = { bg = colors.mantle },
              WinSeparator = { bg = "NONE", fg = colors.base },
              YankHighlight = { bg = colors.surface2 },
              FidgetTask = { fg = colors.subtext2 },
              FidgetTitle = { fg = colors.peach },

              IblIndent = { fg = colors.surface0 },
              IblScope = { fg = colors.overlay0 },

              Boolean = { fg = colors.blue },
              Number = { fg = colors.mauve },
              Float = { fg = colors.mauve },

              PreProc = { fg = colors.blue },
              PreCondit = { fg = colors.blue },
              Include = { fg = colors.blue },
              Define = { fg = colors.blue },
              Conditional = { fg = colors.blue },
              Repeat = { fg = colors.blue },
              Keyword = { fg = colors.blue },
              Typedef = { fg = colors.blue },
              Exception = { fg = colors.blue },
              Statement = { fg = colors.blue },

              Error = { fg = colors.red },
              StorageClass = { fg = colors.blue },
              Tag = { fg = colors.text },
              Label = { fg = colors.blue },
              Structure = { fg = colors.blue },
              Operator = { fg = colors.blue },
              Title = { fg = colors.text },
              Special = { fg = colors.text },
              SpecialChar = { fg = colors.yellow },
              Type = { fg = colors.blue, style = { "bold" } },
              Function = { fg = colors.sky, style = { "bold" } },
              Delimiter = { fg = colors.subtext2 },
              Ignore = { fg = colors.subtext2 },
              Macro = { fg = colors.blue },

              TSAnnotation = { fg = colors.peach },
              TSAttribute = { fg = colors.peach },
              TSBoolean = { fg = colors.blue },
              TSCharacter = { fg = colors.green },
              TSCharacterSpecial = { link = "SpecialChar" },
              TSComment = { link = "Comment" },
              TSConditional = { fg = colors.blue },
              TSConstBuiltin = { fg = colors.blue },
              TSConstMacro = { fg = colors.blue },
              TSConstant = { fg = colors.text },
              TSConstructor = { fg = colors.teal },
              TSDebug = { link = "Debug" },
              TSDefine = { link = "Define" },
              TSEnvironment = { link = "Macro" },
              TSEnvironmentName = { link = "Type" },
              TSError = { link = "Error" },
              TSException = { fg = colors.blue },
              TSField = { fg = colors.text },
              TSFloat = { fg = colors.mauve },
              TSFuncBuiltin = { fg = colors.sky },
              TSFuncMacro = { fg = colors.sky },
              TSFunction = { fg = colors.sky },
              TSFunctionCall = { fg = colors.sky },
              TSInclude = { fg = colors.blue },
              TSKeyword = { fg = colors.blue },
              TSKeywordFunction = { fg = colors.blue },
              TSKeywordOperator = { fg = colors.blue },
              TSKeywordReturn = { fg = colors.blue },
              TSLabel = { fg = colors.blue },
              TSLiteral = { link = "String" },
              TSMath = { fg = colors.blue },
              TSMethod = { fg = colors.sky },
              TSMethodCall = { fg = colors.sky },
              TSNamespace = { fg = colors.teal },
              TSNone = { fg = colors.text },
              TSNumber = { fg = colors.mauve },
              TSOperator = { fg = colors.blue },
              TSParameter = { fg = colors.text },
              TSParameterReference = { fg = colors.text },
              TSPreProc = { link = "PreProc" },
              TSProperty = { fg = colors.text },
              TSPunctBracket = { fg = colors.text },
              TSPunctDelimiter = { link = "Delimiter" },
              TSPunctSpecial = { fg = colors.blue },
              TSRepeat = { fg = colors.blue },
              TSStorageClass = { fg = colors.blue },
              TSStorageClassLifetime = { fg = colors.blue },
              TSStrike = { fg = colors.subtext2 },
              TSString = { fg = colors.green },
              TSStringEscape = { fg = colors.yellow },
              TSStringRegex = { fg = colors.yellow },
              TSStringSpecial = { link = "SpecialChar" },
              TSSymbol = { fg = colors.text },
              TSTag = { fg = colors.blue },
              TSTagAttribute = { fg = colors.teal },
              TSTagDelimiter = { fg = colors.blue },
              TSText = { fg = colors.text },
              TSTextReference = { link = "Constant" },
              TSTitle = { link = "Title" },
              TSTodo = { link = "Todo" },
              TSType = { fg = colors.teal, style = { "bold" } },
              TSTypeBuiltin = { fg = colors.teal, style = { "bold" } },
              TSTypeDefinition = { fg = colors.teal, style = { "bold" } },
              TSTypeQualifier = { fg = colors.blue, style = { "bold" } },
              TSURI = { fg = colors.blue },
              TSVariable = { fg = colors.text },
              TSVariableBuiltin = { fg = colors.blue },

              ["@annotation"] = { link = "TSAnnotation" },
              ["@attribute"] = { link = "TSAttribute" },
              ["@boolean"] = { link = "TSBoolean" },
              ["@character"] = { link = "TSCharacter" },
              ["@character.special"] = { link = "TSCharacterSpecial" },
              ["@comment"] = { link = "TSComment" },
              ["@conceal"] = { link = "Grey" },
              ["@conditional"] = { link = "TSConditional" },
              ["@constant"] = { link = "TSConstant" },
              ["@constant.builtin"] = { link = "TSConstBuiltin" },
              ["@constant.macro"] = { link = "TSConstMacro" },
              ["@constructor"] = { link = "TSConstructor" },
              ["@debug"] = { link = "TSDebug" },
              ["@define"] = { link = "TSDefine" },
              ["@error"] = { link = "TSError" },
              ["@exception"] = { link = "TSException" },
              ["@field"] = { link = "TSField" },
              ["@float"] = { link = "TSFloat" },
              ["@function"] = { link = "TSFunction" },
              ["@function.builtin"] = { link = "TSFuncBuiltin" },
              ["@function.call"] = { link = "TSFunctionCall" },
              ["@function.macro"] = { link = "TSFuncMacro" },
              ["@include"] = { link = "TSInclude" },
              ["@keyword"] = { link = "TSKeyword" },
              ["@keyword.function"] = { link = "TSKeywordFunction" },
              ["@keyword.operator"] = { link = "TSKeywordOperator" },
              ["@keyword.return"] = { link = "TSKeywordReturn" },
              ["@label"] = { link = "TSLabel" },
              ["@math"] = { link = "TSMath" },
              ["@method"] = { link = "TSMethod" },
              ["@method.call"] = { link = "TSMethodCall" },
              ["@namespace"] = { link = "TSNamespace" },
              ["@none"] = { link = "TSNone" },
              ["@number"] = { link = "TSNumber" },
              ["@operator"] = { link = "TSOperator" },
              ["@parameter"] = { link = "TSParameter" },
              ["@parameter.reference"] = { link = "TSParameterReference" },
              ["@preproc"] = { link = "TSPreProc" },
              ["@property"] = { link = "TSProperty" },
              ["@punctuation.bracket"] = { link = "TSPunctBracket" },
              ["@punctuation.delimiter"] = { link = "TSPunctDelimiter" },
              ["@punctuation.special"] = { link = "TSPunctSpecial" },
              ["@repeat"] = { link = "TSRepeat" },
              ["@storageclass"] = { link = "TSStorageClass" },
              ["@storageclass.lifetime"] = { link = "TSStorageClassLifetime" },
              ["@strike"] = { link = "TSStrike" },
              ["@string"] = { link = "TSString" },
              ["@string.escape"] = { link = "TSStringEscape" },
              ["@string.regex"] = { link = "TSStringRegex" },
              ["@string.special"] = { link = "TSStringSpecial" },
              ["@symbol"] = { link = "TSSymbol" },
              ["@tag"] = { link = "TSTag" },
              ["@tag.attribute"] = { link = "TSTagAttribute" },
              ["@tag.delimiter"] = { link = "TSTagDelimiter" },
              ["@text"] = { link = "TSText" },
              ["@text.danger"] = { link = "TSDanger" },
              ["@text.diff.add"] = { link = "diffAdded" },
              ["@text.diff.delete"] = { link = "diffRemoved" },
              ["@text.emphasis"] = { link = "TSEmphasis" },
              ["@text.environment"] = { link = "TSEnvironment" },
              ["@text.environment.name"] = { link = "TSEnvironmentName" },
              ["@text.literal"] = { link = "TSLiteral" },
              ["@text.math"] = { link = "TSMath" },
              ["@text.note"] = { link = "TSNote" },
              ["@text.reference"] = { link = "TSTextReference" },
              ["@text.strike"] = { link = "TSStrike" },
              ["@text.strong"] = { link = "TSStrong" },
              ["@text.title"] = { link = "TSTitle" },
              ["@text.todo"] = { link = "TSTodo" },
              ["@text.todo.checked"] = { link = "Green" },
              ["@text.todo.unchecked"] = { link = "Ignore" },
              ["@text.underline"] = { link = "TSUnderline" },
              ["@text.uri"] = { link = "TSURI" },
              ["@text.warning"] = { link = "TSWarning" },
              ["@todo"] = { link = "TSTodo" },
              ["@type"] = { link = "TSType" },
              ["@type.builtin"] = { link = "TSTypeBuiltin" },
              ["@type.definition"] = { link = "TSTypeDefinition" },
              ["@type.qualifier"] = { link = "TSTypeQualifier" },
              ["@uri"] = { link = "TSURI" },
              ["@variable"] = { link = "TSVariable" },
              ["@variable.builtin"] = { link = "TSVariableBuiltin" },

              ["@lsp.type.class"] = { link = "TSType" },
              ["@lsp.type.comment"] = { link = "TSComment" },
              ["@lsp.type.decorator"] = { link = "TSFunction" },
              ["@lsp.type.enum"] = { link = "TSType" },
              ["@lsp.type.enumMember"] = { link = "TSProperty" },
              ["@lsp.type.events"] = { link = "TSLabel" },
              ["@lsp.type.function"] = { link = "TSFunction" },
              ["@lsp.type.interface"] = { link = "TSType" },
              ["@lsp.type.keyword"] = { link = "TSKeyword" },
              ["@lsp.type.macro"] = { link = "TSConstMacro" },
              ["@lsp.type.method"] = { link = "TSMethod" },
              ["@lsp.type.modifier"] = { link = "TSTypeQualifier" },
              ["@lsp.type.namespace"] = { link = "TSNamespace" },
              ["@lsp.type.number"] = { link = "TSNumber" },
              ["@lsp.type.operator"] = { link = "TSOperator" },
              ["@lsp.type.parameter"] = { link = "TSParameter" },
              ["@lsp.type.property"] = { link = "TSProperty" },
              ["@lsp.type.regexp"] = { link = "TSStringRegex" },
              ["@lsp.type.string"] = { link = "TSString" },
              ["@lsp.type.struct"] = { link = "TSType" },
              ["@lsp.type.type"] = { link = "TSType" },
              ["@lsp.type.typeParameter"] = { link = "TSTypeDefinition" },
              ["@lsp.type.variable"] = { link = "TSVariable" },
            }
          end,
          latte = function(colors)
            return {
              IblIndent = { fg = colors.mantle },
              IblScope = { fg = colors.surface1 },

              LineNr = { fg = colors.surface1 },
            }
          end,
        },
      })

      vim.api.nvim_command("colorscheme catppuccin")
    end,
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "catppuccin",
    },
  },
}
